Repository lichtblick-suite/lichtblick, pull requests merged in 2024-10, with the labels that each got.

#209 Change default layout behavior
  packages/suite-base/src/App.tsx
  packages/suite-base/src/providers/CurrentLayoutProvider/index.test.tsx
  packages/suite-base/src/providers/CurrentLayoutProvider/index.tsx
  packages/suite-base/src/providers/CurrentLayoutProvider/loadDefaultLayouts.test.ts
  packages/suite-base/src/providers/CurrentLayoutProvider/loadDefaultLayouts.ts
  packages/suite-base/src/providers/LayoutManagerProvider.test.tsx
  packages/suite-base/src/providers/LayoutManagerProvider.tsx
Labels: enhancement

#221 Accept relative paths on initial arguments
  packages/suite-desktop/src/main/index.ts
Labels: bug

#223 Fix/open layouts by alphabetic order
  packages/suite-base/src/providers/CurrentLayoutProvider/index.test.tsx
  packages/suite-base/src/providers/CurrentLayoutProvider/index.tsx
Labels: bug

#230 Update LICENSE
  LICENSE
Labels: documentation

#232 Update README.md
  README.md
Labels: documentation
