Repository lichtblick-suite/lichtblick, pull requests merged in 2024-09, with the labels that each got.

#175 Editing pull request template
  .github/pull_request_template.md
Labels: documentation

#176 [Feature] Showing keyboard shortcuts on file menu
  packages/suite-base/src/components/AppBar/AppMenu.tsx
  packages/suite-base/src/components/KeyListener.tsx
  packages/suite-base/src/util/formatKeyboardShortcut.test.ts
Labels: enhancement

#174 [FIX] Replace React.DOM render with createRoot
  benchmark/src/index.tsx
  packages/suite-base/src/components/Chart/index.tsx
  packages/suite-base/src/components/DocumentDropListener.test.tsx
  packages/suite-base/src/panels/CallService/index.tsx
  packages/suite-base/src/panels/Gauge/index.tsx
  packages/suite-base/src/panels/Indicator/index.tsx
  packages/suite-base/src/panels/StateTransitions/index.tsx
  packages/suite-base/src/panels/Teleop/index.tsx
  packages/suite-base/src/panels/ThreeDeeRender/index.tsx
  packages/suite-base/src/panels/createSyncRoot.test.tsx
  packages/suite-base/src/panels/createSyncRoot.tsx
  packages/suite-desktop/src/quicklook/index.tsx
  packages/suite-desktop/src/renderer/index.tsx
  packages/suite-web/src/index.tsx
Labels: bug

#178 [Feature] Button to copy logs on Log panel to clipboard
  packages/suite-base/src/i18n/en/log.ts
  packages/suite-base/src/panels/Log/LogList.tsx
  packages/suite-base/src/panels/Log/LogMessage.tsx
  packages/suite-base/src/panels/Log/formatMessages.test.ts
  packages/suite-base/src/panels/Log/formatMessages.ts
  packages/suite-base/src/panels/Log/index.tsx
Labels: enhancement

#183 Change dependencies for electron-socket on lichtblick-suite
  packages/suite-base/package.json
  packages/suite-base/src/players/Ros1Player.ts
  packages/suite-base/src/players/VelodynePlayer.ts
  packages/suite-desktop/package.json
  packages/suite-desktop/src/preload/index.ts
  packages/suite-desktop/src/renderer/index.tsx
  yarn.lock
Labels: enhancement

#191 Update rosmsg-msgs-common to the Lichtblick
  packages/suite-base/package.json
  packages/suite-base/src/components/TopicList/TopicList.stories.tsx
  packages/suite-base/src/panels/Publish/index.tsx
  packages/suite-base/src/panels/RawMessages/utils.ts
  packages/suite-base/src/panels/Teleop/TeleopPanel.tsx
  packages/suite-base/src/panels/ThreeDeeRender/publish.ts
  packages/suite-base/src/players/FoxgloveWebSocketPlayer/index.ts
  packages/suite-base/src/players/IterablePlayer/ulog/UlogIterableSource.ts
  packages/suite-base/src/util/basicDatatypes.ts
  yarn.lock
Labels: dependencies

#193 Add rosmsg, rosmsg-serialization and rosmsg2-serialization
  packages/mcap-support/package.json
  packages/mcap-support/src/parseChannel.ts
  packages/suite-base/package.json
  packages/suite-base/src/players/FoxgloveWebSocketPlayer/index.ts
  packages/suite-base/src/players/IterablePlayer/BagIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/rosdb3/RosDb3IterableSource.ts
  packages/suite-base/src/players/RosbridgePlayer.ts
  packages/suite-base/src/util/bagConnectionsHelper.ts
  yarn.lock
Labels: dependencies

#194 Update rosbag, roslibjs & comlink
  packages/@types/foxglove__roslibjs/package.json
  packages/@types/lichtblick__roslibjs/index.d.ts
  packages/@types/lichtblick__roslibjs/package.json
  packages/comlink-transfer-handlers/package.json
  packages/den/package.json
  packages/suite-base/package.json
  packages/suite-base/src/players/IterablePlayer/BagIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/WorkerIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/WorkerIterableSourceWorker.ts
  packages/suite-base/src/players/RosbridgePlayer.test.ts
  packages/suite-base/src/players/RosbridgePlayer.ts
  packages/suite-base/src/util/CachedFilelike.ts
  packages/suite-desktop/package.json
  packages/suite-desktop/src/quicklook/getBagInfo.ts
  yarn.lock
Labels: enhancement, dependencies
