Repository lichtblick-suite/lichtblick, pull requests merged in 2024-11, with the labels that each got.

#249 Add unit tests for shared file of state transitions panel
  packages/suite-base/src/panels/StateTransitions/PathLegend.tsx
  packages/suite-base/src/panels/StateTransitions/constants.ts
  packages/suite-base/src/panels/StateTransitions/index.tsx
  packages/suite-base/src/panels/StateTransitions/settings.ts
  packages/suite-base/src/panels/StateTransitions/shared.test.ts
  packages/suite-base/src/panels/StateTransitions/shared.ts
  packages/suite-base/src/panels/StateTransitions/types.ts
Labels: enhancement

#259 [FIX] License type badge fix on readme.md
  README.md
Labels: documentation

#263 [FIX] 3D panel camera sync functionality
  packages/suite-base/src/context/CurrentLayoutContext/index.ts
  packages/suite-base/src/providers/CurrentLayoutProvider/hooks/useUpdateSharedPanelState.test.ts
  packages/suite-base/src/providers/CurrentLayoutProvider/hooks/useUpdateSharedPanelState.ts
  packages/suite-base/src/providers/CurrentLayoutProvider/index.tsx
Labels: bug

#266 Optmize renderState and its related functions
  packages/suite-base/src/components/PanelExtensionAdapter/PanelExtensionAdapter.test.tsx
  packages/suite-base/src/components/PanelExtensionAdapter/renderState.test.ts
  packages/suite-base/src/components/PanelExtensionAdapter/renderState.ts
Labels: enhancement

#271 Fix typo on Sidebars index
  packages/suite-base/src/components/Sidebars/index.tsx
Labels: bug

#285 Add memory estimation feature option back
  packages/suite-base/src/components/AppBar/index.tsx
  packages/suite-base/src/components/ExperimentalFeatureSettings.tsx
  packages/suite-base/src/i18n/en/appSettings.ts
Labels: enhancement
