Repository lichtblick-suite/lichtblick, pull requests merged in 2025-02, with the labels that each got.

#337 Changes to fix indicator panel issue
  packages/suite-base/src/components/Stack.tsx
  packages/suite-base/src/panels/Indicator/Indicator.style.ts
  packages/suite-base/src/panels/Indicator/Indicator.test.tsx
  packages/suite-base/src/panels/Indicator/Indicator.tsx
Labels: bug

#362 Apply new operators to filters
  packages/message-path/src/grammar.ne
  packages/message-path/src/parseMessagePath.test.ts
  packages/message-path/src/types.ts
  packages/suite-base/src/components/MessagePathSyntax/MessagePathInput.test.tsx
  packages/suite-base/src/components/MessagePathSyntax/MessagePathInput.tsx
  packages/suite-base/src/components/MessagePathSyntax/filterMatches.test.ts
  packages/suite-base/src/components/MessagePathSyntax/filterMatches.ts
  packages/suite-base/src/components/MessagePathSyntax/messagePathsForDatatype.test.ts
  packages/suite-base/src/components/MessagePathSyntax/useCachedGetMessagePathDataItems.test.tsx
Labels: enhancement

#369 Fix duplicated header
  packages/suite-base/src/PanelAPI/useConfigById.ts
Labels: bug

#365 CLI flag to open file(s) or a directory on Lichtblick
  packages/suite-base/src/context/Workspace/useOpenFile.tsx
  packages/suite-desktop/package.json
  packages/suite-desktop/src/main/constants.ts
  packages/suite-desktop/src/main/index.ts
  packages/suite-desktop/src/main/resolveSourcePaths.test.ts
  packages/suite-desktop/src/main/resolveSourcePaths.ts
  packages/suite-desktop/src/preload/index.ts
  yarn.lock
Labels: enhancement

#380 Add permissions to run pre build
  .github/workflows/bump-version.yml
Labels: cicd

#371 Update storybook version
  package.json
  yarn.lock
Labels: dependencies

#386 Fix settings API undefined behaviour
  packages/suite-base/src/components/PanelExtensionAdapter/renderState.ts
Labels: bug

#384 Enhancement/give visual feedback when managing extension
  desktop/integration-test/uninstall-extension.test.ts
  packages/suite-base/src/components/ExtensionDetails.test.tsx
  packages/suite-base/src/components/ExtensionDetails.tsx
  packages/suite-base/src/components/ExtensionsSettings/components/ExtensionList/ExtensioList.test.tsx
  packages/suite-base/src/components/ExtensionsSettings/components/ExtensionList/ExtensionList.tsx
  packages/suite-base/src/components/ExtensionsSettings/components/ExtensionListEntry/ExtensionListEntry.tsx
  packages/suite-base/src/components/ExtensionsSettings/index.test.tsx
Labels: enhancement

#372 Story/load multiple mcaps r1
  .eslintrc.yaml
  desktop/integration-test/openFile.test.ts
  eslint-test.ts
  packages/suite-base/package.json
  packages/suite-base/src/Workspace.tsx
  packages/suite-base/src/components/AppBar/AppMenu.tsx
  packages/suite-base/src/components/DataSourceDialog/Start.tsx
  packages/suite-base/src/components/PlayerManager.tsx
  packages/suite-base/src/context/PlayerSelectionContext.ts
  packages/suite-base/src/context/Workspace/constants.ts
  packages/suite-base/src/context/Workspace/useOpenFile.test.tsx
  packages/suite-base/src/context/Workspace/useOpenFile.tsx
  packages/suite-base/src/dataSources/McapLocalDataSourceFactory.test.ts
  packages/suite-base/src/dataSources/McapLocalDataSourceFactory.ts
  packages/suite-base/src/hooks/useIndexedDbRecents.ts
  packages/suite-base/src/i18n/en/appBar.ts
  packages/suite-base/src/i18n/en/openDialog.ts
  packages/suite-base/src/players/IterablePlayer/BagIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/BlockLoader.test.ts
  packages/suite-base/src/players/IterablePlayer/BufferedIterableSource.test.ts
  packages/suite-base/src/players/IterablePlayer/BufferedIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/CachingIterableSource.test.ts
  packages/suite-base/src/players/IterablePlayer/CachingIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/IIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/IterablePlayer.test.ts
  packages/suite-base/src/players/IterablePlayer/Mcap/McapIndexedIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/Mcap/McapIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/Mcap/McapIterableSourceWorker.worker.ts
  packages/suite-base/src/players/IterablePlayer/Mcap/McapUnindexedIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/WorkerIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/WorkerIterableSourceWorker.ts
  packages/suite-base/src/players/IterablePlayer/rosdb3/RosDb3IterableSource.ts
  packages/suite-base/src/players/IterablePlayer/shared/MultiIterableSource.test.ts
  packages/suite-base/src/players/IterablePlayer/shared/MultiIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/shared/types.ts
  packages/suite-base/src/players/IterablePlayer/shared/utils/mergeAsyncIterators.test.ts
  packages/suite-base/src/players/IterablePlayer/shared/utils/mergeAsyncIterators.ts
  packages/suite-base/src/players/IterablePlayer/shared/utils/mergeInitialization.test.ts
  packages/suite-base/src/players/IterablePlayer/shared/utils/mergeInitialization.ts
  packages/suite-base/src/players/IterablePlayer/shared/utils/validateInitialization.test.ts
  packages/suite-base/src/players/IterablePlayer/shared/utils/validateInitialization.ts
  packages/suite-base/src/players/IterablePlayer/ulog/UlogIterableSource.ts
  packages/suite-base/src/test/fixtures/example.mcap
  packages/suite-base/src/testing/builders/InitilizationSourceBuilder.ts
  packages/suite-base/src/util/mergeMultipleFileName.test.ts
  packages/suite-base/src/util/mergeMultipleFileName.ts
  packages/suite-desktop/jest.config.json
  packages/suite-desktop/package.json
  packages/suite-desktop/src/main/StudioWindow.ts
  packages/suite-desktop/src/main/constants.ts
  packages/suite-desktop/src/main/index.ts
  packages/suite-desktop/src/main/injectFilesToOpen.ts
  packages/suite-desktop/src/main/resolveSourcePaths.test.ts
  packages/suite-desktop/src/main/resolveSourcePaths.ts
  packages/suite-desktop/src/main/rosPackageResources.test.ts
  packages/suite-desktop/src/preload/index.ts
  packages/suite-desktop/src/preload/layouts.test.ts
  packages/suite-desktop/src/test/setup.ts
  yarn.lock
Labels: enhancement

#387 Support reading multiple files from URL instead of a single file
  packages/suite-base/src/dataSources/RemoteDataSourceFactory.test.tsx
  packages/suite-base/src/dataSources/RemoteDataSourceFactory.tsx
  packages/suite-base/src/dataSources/constants.ts
  packages/suite-base/src/hooks/useStateToURLSynchronization.ts
  packages/suite-base/src/players/IterablePlayer/IIterableSource.ts
  packages/suite-base/src/players/IterablePlayer/IterablePlayer.ts
  packages/suite-base/src/players/IterablePlayer/Mcap/McapIterableSourceWorker.worker.ts
  packages/suite-base/src/players/IterablePlayer/shared/MultiIterableSource.test.ts
  packages/suite-base/src/players/IterablePlayer/shared/MultiIterableSource.ts
  packages/suite-base/src/players/types.ts
  packages/suite-base/src/util/appURLState.test.ts
  packages/suite-base/src/util/appURLState.ts
  packages/suite-base/src/util/constants.ts
  packages/suite-desktop/src/main/resolveSourcePaths.ts
Labels: enhancement

#388 Migrate CI pipelines to ubuntu-latest
  .github/workflows/ci.yml
  .github/workflows/cloudflare-pages.yml
  .github/workflows/post-release.yml
Labels: cicd
